# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-06 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190705_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')])),
            ],
        ),
        migrations.AlterField(
            model_name='depart',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='depart',
            name='name',
            field=models.CharField(max_length=32, verbose_name='部门名称'),
        ),
        migrations.AddField(
            model_name='user',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Depart'),
        ),
    ]
