# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-09 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128, verbose_name='含正则的URL')),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='标题')),
                ('is_menu', models.BooleanField(default=False, verbose_name='是否是菜单')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='角色名称')),
                ('permissons', models.ManyToManyField(to='rbac.Permission', verbose_name='角色拥有的权限')),
            ],
        ),
    ]
