# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-13 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20190711_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(default=1, max_length=32, verbose_name='URL别名'),
            preserve_default=False,
        ),
    ]
