# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-21 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20190720_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='wight',
            field=models.IntegerField(default=1),
        ),
    ]
